GET http://localhost:8080/mackenzie/areas
###
GET http://localhost:8080/mackenzie/areas/3
###
DELETE http://localhost:8080/mackenzie/areas/3
###
POST http://localhost:8080/mackenzie/areas
Content-Type: application/json

{
    "nome": "Delinquência"
}
###
POST http://localhost:8080/mackenzie/areas
Content-Type: application/json

{
    "nome": "Formação de Quadrilha"
}
###
POST http://localhost:8080/mackenzie/areas
Content-Type: application/json

{
    "nome": "Evasão Fiscal"
}
###
POST http://localhost:8080/mackenzie/areas
Content-Type: application/json

{
    "nome": "Chantagem"
}
###
POST http://localhost:8080/mackenzie/areas
Content-Type: application/json

{
    "nome": "Sequestro"
}
###
PUT http://localhost:8080/mackenzie/areas/2
Content-Type: application/json

{
    "nome": "Roubo"
}
###