POST http://localhost:8080/mackenzie/estudantes
Content-Type: application/json

{
    "nome": "Dedo Sobremesa",
    "email": "dsobremesa@mackenzie.com"
}
###
POST http://localhost:8080/mackenzie/estudantes
Content-Type: application/json

{
    "nome": "Córtex Som",
    "email": "csom@mackenzie.com"
}
###
POST http://localhost:8080/mackenzie/estudantes
Content-Type: application/json

{
    "nome": "Voleibol Costeletas",
    "email": "vcosteletas@mackenzie.com"
}
###
POST http://localhost:8080/mackenzie/estudantes
Content-Type: application/json

{
    "nome": "Rochas Compartimento",
    "email": "rcompartimento@mackenzie.com"
}