POST http://localhost:8080/mackenzie/inscricoes
Content-Type: application/json

{
    "dataInscricao": "2023-05-20",
    "status": "Pendente",
    "mensagemApresentacao": "Ansioso para começar!",
    "estudante": {
        "id": 1
    },
    "vagaEstagio": {
        "id": 1
    }
}
###
POST http://localhost:8080/mackenzie/inscricoes
Content-Type: application/json
{
    "dataInscricao": "2024-04-20",
    "status": "Confirmada",
    "mensagemApresentacao": "Eu amo muito java."
        "estudante": {
        "id": 2
    },
    "vagaEstagio": {
        "id": 2
    }
}

###
POST http://localhost:8080/mackenzie/inscricoes
Content-Type: application/json
{
    "dataInscricao": "2024-03-20",
    "status": "Confirmada",
    "mensagemApresentacao": "Ansioso para começar!"
}

POST http://localhost:8080/mackenzie/inscricoes
Content-Type: application/json
{
    "dataInscricao": "2024-11-02",
    "status": "Pendente",
    "mensagemApresentacao": "Ansioso para começar!"
}
###
POST http://localhost:8080/mackenzie/inscricoes
Content-Type: application/json
{
    "dataInscricao": "2024-01-19",
    "status": "Confirmada",
    "mensagemApresentacao": "Ansioso para começar!"
}

###
POST http://localhost:8080/mackenzie/inscricoes
Content-Type: application/json
{
    "dataInscricao": "2024-07-28",
    "status": "Confirmada",
    "mensagemApresentacao": "Ansioso para começar!"
}

###
POST http://localhost:8080/mackenzie/inscricoes
Content-Type: application/json
{
    "dataInscricao": "2024-06-09",
    "status": "Pendente",
    "mensagemApresentacao": "Ansioso para começar!"
}

###
POST http://localhost:8080/mackenzie/inscricoes
Content-Type: application/json
{
    "dataInscricao": "2024-06-11",
    "status": "Confirmada",
    "mensagemApresentacao": "Ansioso para começar!"
}