POST http://localhost:8080/mackenzie/vagas
Content-Type: application/json

{
    "titulo": "Rei Gusion",
    "descricao": "Dize: Amparo-me no Senhor dos humanos, O Rei dos humanos.",
    "dataPublicacao": "2015-01-07",
    "ativo": true,
    "empresa": {
        "id": 1
    }
}
###
POST http://localhost:8080/mackenzie/vagas
Content-Type: application/json

{
    "titulo": "Marquês Cimejes",
    "descricao": "Em nome de Deus, o Clemente, o Misericordioso.",
    "dataPublicacao": "1972-09-05",
    "ativo": false
}
###
POST http://localhost:8080/mackenzie/vagas
Content-Type: application/json

{
    "titulo": "Duque Zepar",
    "descricao": "Tornou-se austero e voltou as costas, quando o cego foi ter com ele.",
    "dataPublicacao": "1995-04-19",
    "ativo": true
}
###
POST http://localhost:8080/mackenzie/vagas
Content-Type: application/json

{
    "titulo": "Conde Glasya-Labolas",
    "descricao": "Pela aurora, e pelas dez noites, e pelo par e pelo ímpar.",
    "dataPublicacao": "1976-07-04",
    "ativo": false
}
###
POST http://localhost:8080/mackenzie/vagas
Content-Type: application/json

{
    "titulo": "Príncipe Gaap",
    "descricao": "A realidade. Que é a realidade? E o que te fará entender o que significa a realidade?",
    "dataPublicacao": "1986-07-07",
    "ativo": true
}
###
POST http://localhost:8080/mackenzie/vagas
Content-Type: application/json

{
    "titulo": "Presidente Ose",
    "descricao": "Em verdade, enviamos Noé ao seu povo, (dizendo-lhe): Admoesta o teu povo, antes que o açoite um castigo doloroso!",
    "dataPublicacao": "2005-02-14",
    "ativo": false
}